Repository Wanted-Internship-Team-Careerly/Location-Based-Foodie-Service, pull requests merged in 2023-11, with the labels that each got.

#2 [init] 프로젝트 초기 설정
  src/main/java/com/locationbasedfoodieservice/LocationBasedFoodieServiceApplication.java
  src/main/java/com/locationbasedfoodieservice/common/config/JpaConfig.java
  src/main/java/com/locationbasedfoodieservice/common/dto/ApiResponseDto.java
  src/main/java/com/locationbasedfoodieservice/common/entity/Timestamped.java
  src/main/java/com/locationbasedfoodieservice/common/error/CustomErrorCode.java
  src/main/java/com/locationbasedfoodieservice/common/exception/CustomException.java
  src/main/java/com/locationbasedfoodieservice/common/exception/GlobalControllerAdvice.java
  src/main/java/com/locationbasedfoodieservice/member/entity/Member.java
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/entity/RawRestaurant.java
  src/main/java/com/locationbasedfoodieservice/restaurant/entity/Restaurant.java
  src/main/java/com/locationbasedfoodieservice/review/entity/Review.java
  src/main/java/com/locationbasedfoodieservice/sigungu/entity/Sigungu.java
Labels: good first issue

#4 [feature] 회원가입 API
  src/main/java/com/locationbasedfoodieservice/common/config/SecurityConfig.java
  src/main/java/com/locationbasedfoodieservice/common/error/CustomErrorCode.java
  src/main/java/com/locationbasedfoodieservice/member/controller/MemberController.java
  src/main/java/com/locationbasedfoodieservice/member/dto/MemberSignupRequestDto.java
  src/main/java/com/locationbasedfoodieservice/member/entity/Member.java
  src/main/java/com/locationbasedfoodieservice/member/repository/MemberRepository.java
  src/main/java/com/locationbasedfoodieservice/member/service/MemberService.java
  src/test/java/com/locationbasedfoodieservice/member/service/MemberServiceTest.java
Labels: feature

#6 [ci] build test ci 구현
  .github/workflows/develop-ci.yml
Labels: ci

#16 [docs] Issue 템플릿 생성
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: documentation

#13 [feature] 로그인 API
  build.gradle
  src/main/java/com/locationbasedfoodieservice/LocationBasedFoodieServiceApplication.java
  src/main/java/com/locationbasedfoodieservice/common/config/SecurityConfig.java
  src/main/java/com/locationbasedfoodieservice/common/config/auth/LoginMember.java
  src/main/java/com/locationbasedfoodieservice/common/config/auth/LoginService.java
  src/main/java/com/locationbasedfoodieservice/common/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/locationbasedfoodieservice/common/config/jwt/JwtAuthorizationFilter.java
  src/main/java/com/locationbasedfoodieservice/common/config/jwt/JwtProcess.java
  src/main/java/com/locationbasedfoodieservice/common/config/jwt/JwtVO.java
  src/main/java/com/locationbasedfoodieservice/member/dto/MemberLoginRequestDto.java
  src/main/java/com/locationbasedfoodieservice/member/dto/MemberLoginResponseDto.java
  src/main/java/com/locationbasedfoodieservice/member/repository/MemberRepository.java
  src/main/java/com/locationbasedfoodieservice/util/CustomResponseUtil.java
  src/test/java/com/locationbasedfoodieservice/member/controller/MemberControllerTest.java
Labels: feature

#19 [feature] 회원 설정 업데이트 API
  src/main/java/com/locationbasedfoodieservice/common/error/CustomErrorCode.java
  src/main/java/com/locationbasedfoodieservice/member/controller/MemberController.java
  src/main/java/com/locationbasedfoodieservice/member/dto/MemberUpdateRequestDto.java
  src/main/java/com/locationbasedfoodieservice/member/entity/Member.java
  src/main/java/com/locationbasedfoodieservice/member/service/MemberService.java
  src/test/java/com/locationbasedfoodieservice/member/service/MemberServiceTest.java
Labels: feature

#22 [feature] 사용자 정보 API
  src/main/java/com/locationbasedfoodieservice/member/controller/MemberController.java
  src/main/java/com/locationbasedfoodieservice/member/dto/MemberResponseDto.java
  src/main/java/com/locationbasedfoodieservice/member/service/MemberService.java
  src/test/java/com/locationbasedfoodieservice/member/service/MemberServiceTest.java
Labels: feature

#15 [feature] 맛집 평가 API
  build.gradle
  src/main/java/com/locationbasedfoodieservice/common/config/QueryDslConfig.java
  src/main/java/com/locationbasedfoodieservice/common/error/CustomErrorCode.java
  src/main/java/com/locationbasedfoodieservice/restaurant/entity/Restaurant.java
  src/main/java/com/locationbasedfoodieservice/restaurant/repository/RestaurantRepository.java
  src/main/java/com/locationbasedfoodieservice/review/controller/ReviewController.java
  src/main/java/com/locationbasedfoodieservice/review/dto/request/ReviewRequestDto.java
  src/main/java/com/locationbasedfoodieservice/review/dto/response/ReviewResponseDto.java
  src/main/java/com/locationbasedfoodieservice/review/entity/Review.java
  src/main/java/com/locationbasedfoodieservice/review/repository/ReviewRepository.java
  src/main/java/com/locationbasedfoodieservice/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/locationbasedfoodieservice/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/locationbasedfoodieservice/review/service/ReviewService.java
  src/test/java/com/locationbasedfoodieservice/member/controller/MemberControllerTest.java
  src/test/java/com/locationbasedfoodieservice/review/service/ReviewServiceTest.java
Labels: feature

#25 [feature] 경기도 김밥(도시락) OPEN API 스케쥴러 구현
  build.gradle
  src/main/java/com/locationbasedfoodieservice/LocationBasedFoodieServiceApplication.java
  src/main/java/com/locationbasedfoodieservice/common/config/RestTemplateConfig.java
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/entity/RawRestaurant.java
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/repository/RawRestaurantRepository.java
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/scheduler/RawKimbobScheduler.java
Labels: feature

#27 [feature] 데이터 전처리 API
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/entity/RawRestaurant.java
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/repository/RawRestaurantRepository.java
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/scheduler/RawKimbobScheduler.java
  src/main/java/com/locationbasedfoodieservice/restaurant/entity/Restaurant.java
  src/main/java/com/locationbasedfoodieservice/restaurant/repository/RestaurantRepository.java
  src/main/java/com/locationbasedfoodieservice/restaurant/scheduler/RestaurantScheduler.java
Labels: feature

#33 [refactor] 데이터 파이프라인 리팩터링
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/scheduler/RawKimbobScheduler.java
Labels: refactor

#34 [feature] 데이터 파이프라인 complete
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/entity/RawRestaurant.java
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/scheduler/DataType.java
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/scheduler/RawRestaurantScheduler.java
Labels: feature

#37 [refactor] raw restaurant 데이터 갱신 속도 개선
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/entity/RawRestaurant.java
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/repository/RawRestaurantJdbcRepository.java
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/repository/RawRestaurantRepository.java
  src/main/java/com/locationbasedfoodieservice/rawrestaurant/scheduler/RawRestaurantScheduler.java
Labels: refactor

#38 [docs] README 생성
  README.md
  build.gradle
  public/full.png
  public/members_get.png
  public/members_post.png
  public/members_put.png
  public/reviews_post.png
  public/timeline.png
  src/main/java/com/locationbasedfoodieservice/common/config/SwaggerConfig.java
Labels: documentation

#35 [feature] 맛집 평가 상세 정보 API
  src/main/java/com/locationbasedfoodieservice/restaurant/controller/RestaurantController.java
  src/main/java/com/locationbasedfoodieservice/restaurant/dto/response/RestaurantResponseDto.java
  src/main/java/com/locationbasedfoodieservice/restaurant/service/RestaurantService.java
  src/main/java/com/locationbasedfoodieservice/review/dto/response/ReviewResponseDto.java
  src/main/java/com/locationbasedfoodieservice/review/entity/Review.java
  src/main/java/com/locationbasedfoodieservice/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/locationbasedfoodieservice/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/locationbasedfoodieservice/review/service/ReviewService.java
  src/test/java/com/locationbasedfoodieservice/review/service/ReviewServiceTest.java
Labels: feature
